---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.18.1
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library("igraph")
library("visNetwork")
library("htmlwidgets")
```

```{r}
data <- read.csv('network.csv')
```

```{r}
network <- graph.data.frame( data )
```

```{r}
## color keywords red, organisations blue
V(network)$color <- ifelse( V(network)$name %in% data$name, "blue", "red" )
V(network)$type <- V(network)$name %in% data$name
```

```{r}
l <- layout_with_fr( network, grid = "nogrid" )
plot( network, vertex.label = NA, vertex.size = 3, edge.arrow.size = 0, layout = l )
```

```{r}
V( network )$title <- V( network )$name
visIgraph( network ) %>%
 visInteraction(navigationButtons = TRUE) %>%
 visSave(file = "keywords_groups.html")
```

```{r}
research_groups <- bipartite_projection( network , which = "true", remove.type = F)
l <- layout_with_fr( research_groups , grid = "nogrid" )
plot( research_groups, layout = l, vertex.label = NA, vertex.size = 3 )
```

```{r}
V( research_groups )$title <- V( research_groups )$name
visIgraph( research_groups ) %>%
 visInteraction(navigationButtons = TRUE) %>%
 visSave(file = "kgroups.html")
```

```{r}

```
