---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.18.1
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
d <- read.csv( file = 'data/textnet_rasismi.csv', header = F)
head( d )
```

```{r}
summary( d$V1 )
```

## Textnets

[Textnets](https://github.com/cbail/textnets) is a package developed by Chris Bail and helps to develop textual networks in a simple manner. We will now install and develop a simple network from 2000 text examples illustrating racism in Finnish media environment.

```{r}
library(textnets)
```

```{r}
network <- PrepText( d , groupvar = "V1", textvar = "V2", node_type = "groups", 
                    tokenizer = "words",
                    pos = "nouns", remove_stop_words = TRUE, remove_numbers = TRUE,
                    compound_nouns = TRUE, language = "finnish")
textnet <- CreateTextnet( network )
```

```{r}
VisTextNet( textnet )
```

```{r}
TextCommunities( textnet )
```

```{r}
TextCentrality( textnet )
```

```{r}

```
